Update Utils.pm Mojo::File::spurt Mojo::File::spew
omniosorg/zadm pull request #142
Opened 2023-11-10 15:08 UTC by moetiker

Mojo::File::spurt is deprecated in favor of Mojo::File::spew

2023-11-10 15:18 UTC, oetiker submitted a review, later dismissed

2023-11-10 16:09 UTC, hadfl requested changes
since you are on it, can you please change it in `lib/Zadm/Zone/base.pm`, too?

2023-11-11 14:25 UTC, hadfl approved these changes

2023-11-11 14:27 UTC, citrus-it approved these changes

2023-11-11 14:27 UTC, merged